version: '3'

services:
  nginx:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/ssl/