version: '3'

services:
  nginx:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config:/etc/nginx/conf.d:ro
      - ./ssl:/ssl/