version: '3'

services:
  nginx:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - ./config:/etc/nginx/conf.d:ro
      - ./ssl:/ssl/