version: "3"

services:
  search:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    container_name: meilisearch
    command: meilisearch --env="development"
    volumes:
      - ./data:/meili_data